---

- name: "Create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Copy artifact to backend server"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend-app/artifact.tar.gz

- name: "Unarchive backend app files"
  unarchive:
    src: ~/backend-app/artifact.tar.gz
    dest: ~/backend-app
    remote_src: true

- name: "Install node dependencies"
  shell: |
    cd ~/backend-app
    npm i
    
- name: "Run node app with pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node
  environment:
     ENVIRONMENT: production
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./migrations"
     TYPEORM_MIGRATIONS: "./migrations/*.js"
     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}" 